module.exports = {
  videos: [
    {
      id: "t6P4KwtZ0Ic",
      title: "Will Hoge - Even if it breaks your heart",
      link: "https://youtu.be/t6P4KwtZ0Ic",
      thumbnail: "https://i.ytimg.com/vi/t6P4KwtZ0Ic/hqdefault.jpg",
      channel: {
        id: "UC3lF6MEE4uNpBf5o9qj-Vsw",
        name: "charlyei",
        link: "https://www.youtube.com/channel/UC3lF6MEE4uNpBf5o9qj-Vsw",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLQsqL0jVrAz0T4QeoLfEa_PpXjMyWQQKeleG9XqWA=s0?imgmax=0",
      },
      description: "",
      views: 162976,
      uploaded: "11 years ago",
      duration: 223,
    },
    {
      id: "hfYBvtrTsts",
      title: "Will Hoge - Even If It Breaks Your Heart",
      link: "https://youtu.be/hfYBvtrTsts",
      thumbnail: "https://i.ytimg.com/vi/hfYBvtrTsts/hqdefault.jpg",
      channel: {
        id: "UCwgxZ8xogiYL1H-nApzvJBA",
        name: "101.9 KINK.FM",
        link: "https://www.youtube.com/channel/UCwgxZ8xogiYL1H-nApzvJBA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLS2Jw_hGnnqja9LTJJjZekDntkzjUUHjV9OzsNPcg=s0?imgmax=0",
      },
      description: "",
      views: 80426,
      uploaded: "11 years ago",
      duration: 266,
    },
    {
      id: "Q2SZ7t0dDGk",
      title: "Even If It Breaks Your Heart",
      link: "https://youtu.be/Q2SZ7t0dDGk",
      thumbnail: "https://i.ytimg.com/vi/Q2SZ7t0dDGk/hqdefault.jpg",
      channel: {
        id: "UCuY1Z8ah-OtwBZ4jxcKqSSg",
        name: "Will Hoge - Topic",
        link: "https://www.youtube.com/channel/UCuY1Z8ah-OtwBZ4jxcKqSSg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/y9l27e3wSW5RhTz7QXjW-9Ubc3Z53cpaOT2eds0zOjdxcfn0d2GvSd8LFq378iJkJwhZArzy=s0?imgmax=0",
      },
      description: "",
      views: 46560,
      uploaded: "",
      duration: 222,
    },
    {
      id: "P-nvT9a0xbM",
      title: 'WILL HOGE: "Even If It Breaks Your Heart"  +  12.13.2012',
      link: "https://youtu.be/P-nvT9a0xbM",
      thumbnail: "https://i.ytimg.com/vi/P-nvT9a0xbM/hqdefault.jpg",
      channel: {
        id: "UCGnfGcBRjEHzhO2OT3OyfZg",
        name: "TrottermaniaTV TROTTER",
        link: "https://www.youtube.com/channel/UCGnfGcBRjEHzhO2OT3OyfZg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLRioVNOSYdJ5xjsKHIj9zJ3gUT25Ij516JeXSOi=s0?imgmax=0",
      },
      description: "",
      views: 36184,
      uploaded: "8 years ago",
      duration: 532,
    },
    {
      id: "6lIpnORssVE",
      title: "WILL HOGE  -Even If It Breaks Your Heart-",
      link: "https://youtu.be/6lIpnORssVE",
      thumbnail: "https://i.ytimg.com/vi/6lIpnORssVE/hqdefault.jpg",
      channel: {
        id: "UCHuqBktpVBNvsQfCKu8ZVRA",
        name: "Elmo Thamm",
        link: "https://www.youtube.com/channel/UCHuqBktpVBNvsQfCKu8ZVRA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLQoEX5ewylpWDdr2aSGKdRKW7rghzNK88zBD-aY=s0?imgmax=0",
      },
      description: "",
      views: 38393,
      uploaded: "5 years ago",
      duration: 449,
    },
    {
      id: "r0t9AVwHJng",
      title: "Will Hoge - Even If It Breaks Your Heart (Bing Lounge)",
      link: "https://youtu.be/r0t9AVwHJng",
      thumbnail: "https://i.ytimg.com/vi/r0t9AVwHJng/hqdefault.jpg",
      channel: {
        id: "UC-D3WtZYWRP6j_l5keHZriw",
        name: "987TheBull",
        link: "https://www.youtube.com/channel/UC-D3WtZYWRP6j_l5keHZriw",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLT288-sMtIVmyVA-bcz7GpICeK2EKx8u6l6e8Zl=s0?imgmax=0",
      },
      description: "",
      views: 15557,
      uploaded: "7 years ago",
      duration: 237,
    },
    {
      id: "63De445Iy4Y",
      title:
        'Will Hoge "Even If It Breaks Your Heart" 1929 Martin 0-18 at Norman\'s Rare Guitars',
      link: "https://youtu.be/63De445Iy4Y",
      thumbnail: "https://i.ytimg.com/vi/63De445Iy4Y/hqdefault.jpg",
      channel: {
        id: "UCf3r1JdYf6scuGaI0YRkyNg",
        name: "Normans Rare Guitars",
        link: "https://www.youtube.com/channel/UCf3r1JdYf6scuGaI0YRkyNg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLSyNLzhqjQxmlxQ3yug2GW39-ZpJu7RGwt3coQ4iQ=s0?imgmax=0",
      },
      description: "",
      views: 14658,
      uploaded: "2 years ago",
      duration: 278,
    },
    {
      id: "0pyVF0FWvYw",
      title: 'Will Hoge "Even If It Breaks Your Heart"',
      link: "https://youtu.be/0pyVF0FWvYw",
      thumbnail: "https://i.ytimg.com/vi/0pyVF0FWvYw/hqdefault.jpg",
      channel: {
        id: "UCq4MKKFxf_86d1A3sXIYHUA",
        name: "Music City Roots",
        link: "https://www.youtube.com/channel/UCq4MKKFxf_86d1A3sXIYHUA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLSYNSl5lweBeGoCi1vBtICl0tM2W5cXR19bbmUnQw=s0?imgmax=0",
      },
      description: "",
      views: 5587,
      uploaded: "11 years ago",
      duration: 270,
    },
    {
      id: "_eOOpm3KhsI",
      title: "Even If It Breaks Your Heart",
      link: "https://youtu.be/_eOOpm3KhsI",
      thumbnail: "https://i.ytimg.com/vi/_eOOpm3KhsI/hqdefault.jpg",
      channel: {
        id: "UCOIvDItIQheCkk8tD_xKm1Q",
        name: "Eli Young Band",
        link: "https://www.youtube.com/channel/UCOIvDItIQheCkk8tD_xKm1Q",
        verified: true,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLS9L696h7HB6J6Wnp_bu7HoWRwoFZYFBTyCo-8wxw=s0?imgmax=0",
      },
      description: "",
      views: 1364953,
      uploaded: "",
      duration: 221,
    },
    {
      id: "6V8SC907YSY",
      title: "Will Hoge - Even If It Breaks Your Heart",
      link: "https://youtu.be/6V8SC907YSY",
      thumbnail: "https://i.ytimg.com/vi/6V8SC907YSY/hqdefault.jpg",
      channel: {
        id: "UCg4rrHPu4DhuoUe4MK5hI4A",
        name: "Bobby Bones Show",
        link: "https://www.youtube.com/channel/UCg4rrHPu4DhuoUe4MK5hI4A",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLTbHZxmoP0GAwioY5I3O6dC_WBlgfMIKwFLGpRvTw=s0?imgmax=0",
      },
      description: "",
      views: 7637,
      uploaded: "7 years ago",
      duration: 174,
    },
    {
      id: "3PCVA5j5-J4",
      title: "Will Hoge - Even If It Breaks Your Heart - Live at Lightning 100",
      link: "https://youtu.be/3PCVA5j5-J4",
      thumbnail: "https://i.ytimg.com/vi/3PCVA5j5-J4/hqdefault.jpg",
      channel: {
        id: "UCyCCCtmCNAvGueSo2PlgUqA",
        name: "Lightning 100",
        link: "https://www.youtube.com/channel/UCyCCCtmCNAvGueSo2PlgUqA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLRblSHxftVAeFEU_nacyMVk4wNVvmjaBpflumjFSw=s0?imgmax=0",
      },
      description: "",
      views: 16097,
      uploaded: "11 years ago",
      duration: 208,
    },
    {
      id: "IGserj5uwQA",
      title: 'Will Hoge "Even If It Breaks Your Heart"',
      link: "https://youtu.be/IGserj5uwQA",
      thumbnail: "https://i.ytimg.com/vi/IGserj5uwQA/hqdefault.jpg",
      channel: {
        id: "UCq4MKKFxf_86d1A3sXIYHUA",
        name: "Music City Roots",
        link: "https://www.youtube.com/channel/UCq4MKKFxf_86d1A3sXIYHUA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLSYNSl5lweBeGoCi1vBtICl0tM2W5cXR19bbmUnQw=s0?imgmax=0",
      },
      description: "",
      views: 37464,
      uploaded: "9 years ago",
      duration: 220,
    },
    {
      id: "wtQP9EBfpsQ",
      title: 'Will Hoge "Even If It Breaks Your Heart"',
      link: "https://youtu.be/wtQP9EBfpsQ",
      thumbnail: "https://i.ytimg.com/vi/wtQP9EBfpsQ/hqdefault.jpg",
      channel: {
        id: "UCnll0k_K37_0iFuvZENbLDQ",
        name: "scruffycityroots",
        link: "https://www.youtube.com/channel/UCnll0k_K37_0iFuvZENbLDQ",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLQ-kNjgczvaaU3or1scUTMlD0JtXi39o8wGBy2b=s0?imgmax=0",
      },
      description: "",
      views: 414,
      uploaded: "9 years ago",
      duration: 340,
    },
    {
      id: "2aWB6LD2jtQ",
      title: "Will Hoge - Even If It Breaks Your Heart - 615 Day Session",
      link: "https://youtu.be/2aWB6LD2jtQ",
      thumbnail: "https://i.ytimg.com/vi/2aWB6LD2jtQ/hqdefault.jpg",
      channel: {
        id: "UCyCCCtmCNAvGueSo2PlgUqA",
        name: "Lightning 100",
        link: "https://www.youtube.com/channel/UCyCCCtmCNAvGueSo2PlgUqA",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLRblSHxftVAeFEU_nacyMVk4wNVvmjaBpflumjFSw=s0?imgmax=0",
      },
      description: "",
      views: 3673,
      uploaded: "9 years ago",
      duration: 182,
    },
    {
      id: "jMOVkdbnapw",
      title: "Even If It Breaks Your Heart",
      link: "https://youtu.be/jMOVkdbnapw",
      thumbnail: "https://i.ytimg.com/vi/jMOVkdbnapw/hqdefault.jpg",
      channel: {
        id: "UCuY1Z8ah-OtwBZ4jxcKqSSg",
        name: "Will Hoge - Topic",
        link: "https://www.youtube.com/channel/UCuY1Z8ah-OtwBZ4jxcKqSSg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/y9l27e3wSW5RhTz7QXjW-9Ubc3Z53cpaOT2eds0zOjdxcfn0d2GvSd8LFq378iJkJwhZArzy=s0?imgmax=0",
      },
      description: "",
      views: 1120,
      uploaded: "",
      duration: 222,
    },
    {
      id: "W8qe0hay2y0",
      title: 'WILL HOGE: "Even if It Breaks Your Heart"  08.02.2012',
      link: "https://youtu.be/W8qe0hay2y0",
      thumbnail: "https://i.ytimg.com/vi/W8qe0hay2y0/hqdefault.jpg",
      channel: {
        id: "UCGnfGcBRjEHzhO2OT3OyfZg",
        name: "TrottermaniaTV TROTTER",
        link: "https://www.youtube.com/channel/UCGnfGcBRjEHzhO2OT3OyfZg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLRioVNOSYdJ5xjsKHIj9zJ3gUT25Ij516JeXSOi=s0?imgmax=0",
      },
      description: "",
      views: 937,
      uploaded: "9 years ago",
      duration: 275,
    },
    {
      id: "RvNZX_AAjQU",
      title: "Will Hoge - Even If It Breaks Your Heart",
      link: "https://youtu.be/RvNZX_AAjQU",
      thumbnail: "https://i.ytimg.com/vi/RvNZX_AAjQU/hqdefault.jpg",
      channel: {
        id: "UCtCu5tu1gfIsn_Yw6cK60Yw",
        name: "lesleyrebecca",
        link: "https://www.youtube.com/channel/UCtCu5tu1gfIsn_Yw6cK60Yw",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLQsiV6s8MvhwYFeKYhlRE5JkSFtynPa2duN3QAy=s0?imgmax=0",
      },
      description: "",
      views: 28693,
      uploaded: "12 years ago",
      duration: 158,
    },
    {
      id: "_xRvU1NellM",
      title: "Will Hoge :: Even if it Breaks Your Heart",
      link: "https://youtu.be/_xRvU1NellM",
      thumbnail: "https://i.ytimg.com/vi/_xRvU1NellM/hqdefault.jpg",
      channel: {
        id: "UCgI0BOZrK8XGxltqNR3EDQg",
        name: "Rich Redmond",
        link: "https://www.youtube.com/channel/UCgI0BOZrK8XGxltqNR3EDQg",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLSui8D_S6gIiUhx0N2l605AkQmUElVtt4vlbsNU=s0?imgmax=0",
      },
      description: "",
      views: 210,
      uploaded: "5 months ago",
      duration: 2708,
    },
    {
      id: "zXPcLJxMaXc",
      title:
        "Will Hoge - Even If It Breaks Your Heart & Daddy Was A Gambling Man [LIVE]",
      link: "https://youtu.be/zXPcLJxMaXc",
      thumbnail: "https://i.ytimg.com/vi/zXPcLJxMaXc/hqdefault.jpg",
      channel: {
        id: "UCLJTCHyNwtC2fk_fJ9j5wIw",
        name: "KORN Country 100.3",
        link: "https://www.youtube.com/channel/UCLJTCHyNwtC2fk_fJ9j5wIw",
        verified: false,
        thumbnail:
          "https://yt3.ggpht.com/ytc/AKedOLRRPATmV2qMKOlCm5fL9PLzj0_k_16h-3LR5PIxFg=s0?imgmax=0",
      },
      description: "",
      views: 947,
      uploaded: "7 years ago",
      duration: 833,
    },
  ],
  playlists: [],
  streams: [],
  channels: [],
};
